name: run main.go
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 */1 * *"
jobs:
  build:
    runs-on: alpine:3.12.0
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14.1'
    - run: go run main.go
