name: run main.go
on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/28 22-17 * * *"
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14.1'
    - run: go run main.go
